export const ApplicationScreens = {
    HOME_TAB: "HOME_TAB",
    ADD_TAB: "ADD_TAB",
    PROFILE_TAB: "PROFILE_TAB",
    MENU_TAB: "MENU_TAB",
    PRODUCTS_SCREEN: "PRODUCTS_SCREEN",
    PRODUCT_ITEM_SCREEN: "PRODUCT_ITEM_SCREEN",
    ADD_PRODUCT_SCREEN: "ADD_PRODUCT_SCREEN",
    PROFILE_SCREEN: "PROFILE_SCREEN",
    MENU_SCREEN: "MENU_SCREEN",
};